### ISSUE TITLE
Add cargo test step to CI

### ISSUE THREAD

**Issue by nnmm** [ros2-rust/ros2_rust#112]
This step would be a stopgap until `colcon test` is implemented for the `ament_cargo` build type.

**Comment by mohitsaxenaknoldus** [comment]
I'll do it.

**Comment by mohitsaxenaknoldus** [comment]
Do we run this for every package?

**Comment by nnmm** [comment]
Let's exclude `rclrs_examples` for now too.

**Comment by nnmm** [comment]
Forgot to close this!
