### ISSUE TITLE
Add rustdoc check step to CI

### ISSUE THREAD

**Issue by nnmm** [ros2-rust/ros2_rust#113]
We can check with `cargo rustdoc -- -D warnings` whether a package's documentation contains any warnings or errors. This could be another step in the CI pipeline.

**Comment by nnmm** [comment]
Yes, of course!

**Comment by mohitsaxenaknoldus** [comment]
> Yes, of course!

Thanks! PR: https://github.com/ros2-rust/ros2_rust/pull/117
