### ISSUE TITLE
Add function to get non-ROS arguments

### ISSUE THREAD

**Issue by nnmm** [ros2-rust/ros2_rust#147]
When the context receives command line arguments, it only parses the ones between `--ros-args` and a `--`. The context could have a function to return a list of command line arguments _not_ parsed by ROS, for further processing with `clap` or so. 

This should be done using functions from https://github.com/ros2/rcl/blob/foxy/rcl/include/rcl/arguments.h, and the `rcl_arguments_t` instance stored in the `rcl_context_t`.

**Comment by Nizerlak** [comment]
I think this issue can be closed because of #210 merge.

**Comment by nnmm** [comment]
True!
