### ISSUE TITLE
Add functions to get topic name to publisher and subscription

### ISSUE THREAD

**Issue by nnmm** [ros2-rust/ros2_rust#148]
The `rcl_subscription_get_topic_name` and `rcl_publisher_get_topic_name` functions should be wrapped and added to the `Subscription` and `Publisher`, analogously to https://github.com/ros2-rust/ros2_rust/pull/143.

**Comment by surfertas** [comment]
Seems like this was closed by #194 . Am looking for issues to work on.

**Comment by nnmm** [comment]
That's true. How about https://github.com/ros2-rust/ros2_rust/issues/147?
