### ISSUE TITLE
Node constructor method become verbose?

### ISSUE THREAD

**Issue by Soya-Onishi** [ros2-rust/ros2_rust#157]
Through some works for #142 , there is a point I want to ask about.

`Context` and `Node` have constructor methods for `Node` and current implementation is aware of each patterns like only name and with namespace. However, after supporting node options, these constructor method can be 4 patterns like below.

- only name (`Node::new`)
- name and namespace (`Node::new_with_namespace`)
- name and options (need implementation if need)
- name, namespace and options (implement now in [here](https://github.com/Soya-Onishi/ros2_rust/blob/15dad51a979d617ec09e7edc0676253ebc3e1ff5/rclrs/src/node/mod.rs#L64))

For now, I only implement name, namespace and options pattern for passing custom options to node constructor.

Inferring from rclcpp [Node constructor parameters](https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Node.html), there will not be more parameters, but I feel current implementation has already be about to become verbose.

For simpleness, should those constructors be replaced to builder pattern?

**Comment by nnmm** [comment]
I think that's a good idea. IMO the builder should allow setting the node options directly, instead of exposing a `NodeOptions` struct, like so:

```
NodeBuilder::new("node_name")
  .namespace("my_ns")
  .use_global_arguments(true)
  .build()
```

Such a builder pattern neatly fits the fact that only the node name has no default value.

Then we can delete the new_with_namespace constructor.
