### ISSUE TITLE
Support Box<T: Message> argument type to subscription callbacks 

### ISSUE THREAD

**Issue by nnmm** [ros2-rust/ros2_rust#185]
We should also allow sending and receiving `Box<T>` where `T: Message`, in addition to `T` (and, in the case of publishers, `&T`) – sometimes that's more convenient or efficient.

For publishers, it would be straightforward: Change the `Cow` to something that also has a variant for boxed values.

For subscriptions, I don't know if we can somehow derive the concrete type (`Box<T>` vs `T`) from the callback given. But one way that would work is to give subscriptions an additional generic parameter for the concrete type.

**Comment by LaVieEstDure** [comment]
Currently `Subscription::new` takes `callback: F` where `F: FnMut(T) + 'static + Send` and `T: Message`. We can have `Box<MsgType>` still fit this if we `impl<T: Message> Message for Box<T>` and forward the behaviour. If no one else is working on this, I can have a crack at this
