### ISSUE TITLE
Replace parking_lot mutexes with stdlib

### ISSUE THREAD

**Issue by nnmm** [ros2-rust/ros2_rust#216]
Starting with Rust 1.62, the standard lib mutexes have roughly equal performance to parking_lot: https://github.com/rust-lang/rust/pull/95035

IMO we could replace parking_lot with the standard lib mutexes throughout our code.

**Comment by jhdcs** [comment]
This looks pretty good to me! It will help reduce the size of the library as well!

The only snag I can foresee is that we will have to deal with the possibility of `poison`ed Mutexes again, unless `std` did away with that?

**Comment by nnmm** [comment]
Yes, the `lock()` calls will be slightly uglier, but lock poisoning is a safety feature, so I'd say it's a net win.

**Comment by esteve** [comment]
Sounds good to me. The more we can use from `stdlib` the better :slightly_smiling_face:
