### ISSUE TITLE
Rebuild the workspace on change

### ISSUE THREAD

**Issue by bergercookie** [ros2-rust/ros2_rust#22]
I've successfully built the ros2_rust repo as part of my ROS workspace and have successfully run the talker/listener example.

However, If I make some changes to the the code, say in `subscription.rs` and re-run `colcon build` the changes to the file don't seem to have any effect.

I know they should have an effect because for example I'm introducing a clear syntax error.
Additionally I haven't managed to rebuild the rust code either when I'm passing `--cmake-configure` or `--cmake-clean-cache` to `colcon`.

Only way I've manged to do this is by removing completely the `install`, `build` directories

is there something I'm missing?

Thanks

**Comment by nnmm** [comment]
I'm closing this issue since the way packages are built has changed and the new build system should pick up changes to source files.
