### ISSUE TITLE
Is there an equivalent to the rclpy get_node_names() method in rclrs

### ISSUE THREAD

**Issue by James-O2** [ros2-rust/ros2_rust#233]
in rclpy land you can get all the active nodes by running get_node_names(). Does rclrs have that utility implemented?

https://docs.ros2.org/foxy/api/rclpy/api/node.html

**Comment by christopherjreid** [comment]
I actually just opened a PR, #234, that provides this functionality

**Comment by christopherjreid** [comment]
@nnmm  I think we can close this and #123 now that #234 has closed, right?

**Comment by nnmm** [comment]
@christopherjreid Definitely, thanks for reminding me.
