### ISSUE TITLE
Error when generating code for sensor_msgs/JoyFeedback

### ISSUE THREAD

**Issue by LoyVanBeek** [ros2-rust/ros2_rust#26]
The `sensor_msgs/JoyFeedback` message has a field called `type`, which is a keyword in Rust. 
A suggested fix is to prefix with `r#` but of course this should be done automagically.

Being a Rust n00b, I don't know the effect this has on how the code can be used and other effects.

**Comment by nnarain** [comment]
Ya this needs to be fixed. `rosidl_python` prints a warning when keywords are used. Debated on adding this to the Dashing+ support MR but wanted keep it as simple as possible.

**Comment by nnmm** [comment]
Closed by #30.
