### ISSUE TITLE
Create github pages with rustdoc documentation

### ISSUE THREAD

**Issue by nnmm** [ros2-rust/ros2_rust#275]
docs.rs cannot build `rclrs` since it requires a ROS 2 installation, and as such it can't display the rustdocs: https://docs.rs/crate/rclrs/0.2.0

To make ros2-rust more accessible, we should host the docs ourselves, and GitHub pages are probably the easiest way. They could be updated in a CI step.

Crates that should be covered are `rclrs`, `rosidl_runtime_rs`, and perhaps generated message crates for `common_interfaces` packages (they are built in CI anyway).

**Comment by esteve** [comment]
I agree, though I'd use readthedocs to host the documentation, a significant number of open source projects host their documentation there. I'd leave Github pages for non-documentation content.

**Comment by michalfita** [comment]
@nnmm Have you read the https://forge.rust-lang.org/docs-rs/add-dependencies.html?

**Comment by nnmm** [comment]
@michalfita Unfortunately, ROS 2 is not in the standard Ubuntu 20.04 repositories.

**Comment by michalfita** [comment]
It may be tough call, but for `ros2-rust` to go mainstream docs.rs is mandatory. Either raise good cause and reason and reqest adding ROS2 to their Docker
or
Fork it with required dependencies and run own copy... Question remains open where to host it.

That BTW sounds like a feature to allow certain serious maintainers to provide own Docker image to generate documentation 🤔

**Comment by maspe36** [comment]
As of https://github.com/ros2-rust/ros2_rust/pull/347, we now generate docs.rs documentation. This suggestion is now obsolete.
