### ISSUE TITLE
Matrix Chat

### ISSUE THREAD

**Issue by whiteplatin** [ros2-rust/ros2_rust#286]
Is there still a Matrix Chat ? 
When I click on the link under contributions.md , it says something like not found anymore.

**Comment by nnmm** [comment]
Does https://app.element.io/#/room/!AiYXdTWExqamTdatBl:matrix.org work for you?

**Comment by whiteplatin** [comment]
Yes it works, did not know it was under "Rust WG". I was expecting something like "ROS2 Rust", something to that extent.
