### ISSUE TITLE
Does ROS2_Rust support .srv code generation?

### ISSUE THREAD

**Issue by ekkaiasmith** [ros2-rust/ros2_rust#305]
Hello,
I would like to define a user type for client/service nodes, but I don't see how to generate the code for a .srv

**Comment by nnmm** [comment]
You should be able to just create a package containing your .srv like you would for C++ or Python, and follow https://github.com/ros2-rust/ros2_rust/blob/main/docs/building.md. Does that not work?

cc @ros2-rust/dev

**Comment by ekkaiasmith** [comment]
I didn't know it worked that way. Everything is working fine, thank you!

**Comment by nnmm** [comment]
Okay, great!
