### ISSUE TITLE
Zero copy publisher example fails

### ISSUE THREAD

**Issue by bxtbold** [ros2-rust/ros2_rust#317]
I have been testing the `examples_rclrs_minimal_pub_sub` pkg, but zero copy publisher doesn't seem to be working properly.
- I have tested the node on Ubuntu 22.04 (ROS2 Humble) and implemented CycloneDDS.

```bash
$ ros2 run examples_rclrs_minimal_pub_sub zero_copy_publisher
Error: Unsupported return code (RCL_RET_UNSUPPORTED).

Caused by:
    Loaning is not supported
[ros2run]: Process exited with failure 1
```

As far as I know, using load messages is considered experimental in ROS2. I would appreciate if one of contributors guide me to resolve this issue? Thanks in advance :)

**Comment by esteve** [comment]
@bxtbold could you elaborate a bit how you fixed it so that other users who have the same issue can solve it? Thanks
