### ISSUE TITLE
Fix documentation now that rclrs is on crates.io

### ISSUE THREAD

**Issue by Carter12s** [ros2-rust/ros2_rust#334]
Was doing a pass through the documentation to familiarize myself with the crate. Found multiple "*Note: once `rclrs` is published on crates.io" blurbs in docs/building.md

I do believe rclrs is now on crates.io and this documentation should be updated. Not familiar enough with the crate at the moment to make this changes, so flagging this issue, but I intend to take a stab at it myself later.

**Comment by esteve** [comment]
@Carter12s thanks for filing this ticket. I believe #379 should address this issue, could you have a look at it when you have a moment? Thanks.
