### ISSUE TITLE
Improve support for rust language analyzers

### ISSUE THREAD

**Issue by ruffsl** [ros2-rust/ros2_rust#34]
During the last Rust WG meeting, members reported difficulties in trying to get rclrs to play nicely with VSCode + Rust-Analyzer. In particular, one of the hangups is that rust-analyzer gets confused by auto generated messages, and can’t recognize them as types. This could tie into some of the other tickets for improving message generation and build integration with cargo, although this ticket specifically tracks issues for improving support for rust language analyzers such as rls or rust-analyzer:

* https://github.com/rust-analyzer/rust-analyzer
* https://github.com/rust-lang/rls

This'll not only aid in rclrs development, but also help downstream users creating their own ROS Rust packages.

Related:
* https://github.com/ros2-rust/ros2_rust/issues/11
* https://github.com/ros2-rust/ros2_rust/issues/13

**Comment by ruffsl** [comment]
@kjeremy @jhdcs @gbiggs , I recall you had started discussing this topic on the Rust WG proposal post along this thread:
https://discourse.ros.org/t/proposal-rust-working-group-for-ros/16993/30

**Comment by kjeremy** [comment]
@ruffsl

As mentioned in that thread the issue is that the included examples copy the `Cargo.toml` and inject entries for the messages during build. If you open the build space folder in vscode then `rust-analyzer` will give you types. The easiest solution from the `rls`/`rust-analyzer` POV would be to include those in the `Cargo.toml` or maybe `build.rs` from the beginning.

**Comment by jhdcs** [comment]
> The easiest solution from the `rls`/`rust-analyzer` POV would be to include those in the `Cargo.toml` or maybe `build.rs` from the beginning.

I think that this may be the best solution. I can forsee people using `rclrs` not knowing that they have to open the build space folder for `rclrs` in order to get types for whatever crate they're working on. This would be especially bad if they didn't download ROS 2 from source.

**Comment by gbiggs** [comment]
This sounds like we should expect users to do with `Cargo.toml` what they have to do with `CMakeLists.txt` in a CMake or `ament_cmake` package: Include the message information in two places. It's as lovely a solution as it is in those other packages, but it seems it would solve the problem.
