### ISSUE TITLE
does ros2_rust support autogeneration of code from .idl and .msg files, is there any example implementation to autogenerate rust nodes from .idl/.msg files?

### ISSUE THREAD

**Issue by vignesh-tw** [ros2-rust/ros2_rust#348]

**Comment by maspe36** [comment]
We can generate rust code for idl and msg files thanks to the [rosidl_generator_rs](https://github.com/ros2-rust/ros2_rust/tree/main/rosidl_generator_rs) and [rosidl_runtime_rs](https://github.com/ros2-rust/ros2_rust/tree/main/rosidl_runtime_rs) packages in this repo. 

In the [rclrs_example_msgs](https://github.com/ros2-rust/ros2_rust/tree/main/rclrs_example_msgs) package, we define a few .msg files and then we consume them in [message_demo](https://github.com/ros2-rust/ros2_rust/tree/main/examples/message_demo) example. There is nothing special about the `rclrs_example_msgs` package, the "magic" is in `message_demo`'s package.xml where we specify our dependency on the `rosidl_runtime_rs` package. 

As for the second part of your question, there is no way to generate _**nodes**_ from just .idl/.msg files. To quote the [ROS 2 docs](https://docs.ros.org/en/iron/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Nodes/Understanding-ROS2-Nodes.html#summary) 

> A node is a fundamental ROS 2 element that serves a single, modular purpose in a robotics system.

So having codegen for types defined in .idl/.msg files is different from automatically generating a node. You'll still need to write code that uses your auto-generated types.
