### ISSUE TITLE
Audit drop ordering for rcl handles

### ISSUE THREAD

**Issue by mxgrey** [ros2-rust/ros2_rust#377]
We've noticed that there may be issues with drop orders of rcl handles that are held by rclrs structs, e.g. #372 .

I'm not certain that #372 fixed all the problems that may exist, so I'll keep auditing the structs and drop order strategy to make sure it's sound.

Maintainers can feel free to assign this ticket to me.

**Comment by esteve** [comment]
@mxgrey thanks for looking into it

**Comment by mxgrey** [comment]
Closed by #386
