### ISSUE TITLE
Documentation incorrect regarding BoundedSequence.is_empty()

### ISSUE THREAD

**Issue by imdex-matthew** [ros2-rust/ros2_rust#411]
Documentation incorrectly indicates that you can check a BoundedSequence is empty.

/// // The default bounded sequence is empty
/// assert!(BoundedSequence::<i32, 5>::default().is_empty());

This results in the following error:

thread '...' panicked at library/core/src/panicking.rs:220:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`

**Comment by maspe36** [comment]
Hey @imdex-matthew, I took a loot at this, and it actually wasn't incorrect documentation. This was a bug in our implementation. 

Now that #416 is merged, this should be fixed
