### ISSUE TITLE
Move repository to github.com/ros2-rust and add members

### ISSUE THREAD

**Issue by esteve** [ros2-rust/ros2_rust#8]
Hey @lelongg, I've opened this ticket to move this repository to the github.com/ros2-rust organization. Do you want me to add you as a member? You've done a great job with #3 and I just think it's fair to add you as member, but I understand if you'd rather not have this responsibility :-)

**Comment by lelongg** [comment]
Thanks ! I'd be glad to offer my help on this project.
I lack experience with open source but I think it would be a great opportunity for me to get more involved.

**Comment by esteve** [comment]
@lelongg done. Thanks for joining the team :-)
